# Give KCC for this project's namespace permission to read KCC resources in the networking namespace.
# This allows GKE and GCE instances to reference the shared network in the networking namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: networking/cnrm-network-viewer-project-id
  name: cnrm-network-viewer-project-id # kpt-set: cnrm-network-viewer-${project-id}
  namespace: networking # kpt-set: ${networking-namespace}
roleRef:
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-project-id # kpt-set: cnrm-controller-manager-${project-id}
    namespace: cnrm-system
    kind: ServiceAccount
---
# Give KCC for this project's namespace permission to read KCC resources in the projects namespace.
# This allows IAMMemberPolicy in this project's namespace to reference the project in the projects namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: projects/cnrm-project-viewer-project-id
  name: cnrm-project-viewer-project-id # kpt-set: cnrm-project-viewer-${project-id}
  namespace: projects # kpt-set: ${projects-namespace}
roleRef:
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-project-id # kpt-set: cnrm-controller-manager-${project-id}
    namespace: cnrm-system
    kind: ServiceAccount
