name: Create the landing zone

on:
  workflow_dispatch:
    inputs:
      departmentName:
        type: string
        required: true

      serviceName:
        type: string
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get kpt package
        uses: docker://gcr.io/kpt-dev/kpt:v1.0.0-beta.9
        with:
          args: pkg get https://github.com/yoshimasak/configcontroller-demorepo.git/templates/hierarchy@main manifests/landing-zone/hierarchy/${{ inputs.departmentName }}

      - name: Change permission
        run: sudo chown -R runner:docker manifests/landing-zone/hierarchy/${{ inputs.departmentName }}

      - name: Modify setters.yaml
        run: "sed -i -e 's/1234567890123/153064141304/' -e 's/department/${{ inputs.departmentName }}/' -e 's/service/${{ inputs.serviceName }}/' manifests/landing-zone/hierarchy/${{ inputs.departmentName }}/hierarchy.yaml"
            
      - name: Git push
        run: |
          git config --global user.email "admin@example.com"
          git config --global user.name "Administrator"
          git add .
          git commit -m "Create folder for ${{ inputs.departmentName }} dept. ${{ inputs.serviceName }} service"
          git push origin dev
          
      - name: Create pull request
        run: gh pr create -B "main" -t "Create ${{ inputs.departmentName }} dept ${{ inputs.serviceName }} service folder" -H dev -b "Review request for creating a new folder."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
