name: Create the landing zone

on:
  workflow_dispatch:
    inputs:
      department:
        type: string
        required: true

      service:
        type: string
        required: true

      landingzone_setters:
        type: string
        required: true

      hierarchy_setters:
        type: string
        required: true

      project_setters:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create project directory
        run: |
          mkdir manifests/landing-zone/projects/${{ inputs.department }}

      - name: Get hierarchy kpt package
        uses: docker://gcr.io/kpt-dev/kpt:v1.0.0-beta.9
        with:
          args: pkg get https://github.com/yoshimasak/configcontroller-demorepo.git/templates/hierarchy@main manifests/landing-zone/hierarchy/${{ inputs.department }}

      - name: Get project kpt package
        uses: docker://gcr.io/kpt-dev/kpt:v1.0.0-beta.9
        with:
          args: pkg get https://github.com/yoshimasak/configcontroller-demorepo.git/templates/projects@main manifests/landing-zone/projects/${{ inputs.department }}/${{ inputs.service }}

      - name: Change permission
        run: |
          sudo chown -R runner:docker manifests/landing-zone/hierarchy/${{ inputs.department }}
          sudo chown -R runner:docker manifests/landing-zone/projects/${{ inputs.department }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm install js-yaml
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const js-yaml = require('js-yaml')

            var payload = ${{ inputs.landingzone_setters }}
            var json = JSON.parse(JSON.stringify(payload))
            var yaml = js-yaml.dump(json)
            console.log(yaml)

            fs.writeFile('manifests/landing-zone/setters.yaml', yaml, 'utf8', (err) => {
              if (err) {
                console.error(err.message)
              }
            })

            payload = ${{ inputs.hierarchy_setters }}
            json = JSON.parse(JSON.stringify(payload))
            yaml = js-yaml.dump(json)
            console.log(yaml)

            fs.writeFile('manifests/landing-zone/hierarchy/${{ inputs.department }}/setters.yaml', yaml, 'utf8', (err) => {
              if (err) {
                console.error(err.message)
              }
            })

            payload = ${{ inputs.project_setters }}
            json = JSON.parse(JSON.stringify(payload))
            yaml = js-yaml.dump(json)
            console.log(yaml)

            fs.writeFile('manifests/landing-zone/projects/${{ inputs.department }}/${{ inputs.service }}/setters.yaml', yaml, 'utf8', (err) => {
              if (err) {
                console.error(err.message)
              }
            })

      - name: Git push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add manifests/landing-zone/
          git commit -m ":robot: Create folder at `date --iso-8601=seconds`"
          git push origin main:dev

      - name: Create pull request
        run: gh pr create -B "main" -t "Create ${{ inputs.department }} folder" -H dev -b "Review request for creating a new folder."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
